- Payments screen has been designed.
Netmera/netmera-fintech-android pull request #1
Opened 2023-03-09 10:36 UTC by yasirinitialcode

## Related Issue
- Payments screen design. 

ISSUE LINK: https://app.asana.com/0/1203144541549209/1204097456360678

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?
Tested with Redmi Note 7 and Samsung Galaxy M12

## Screenshots or Sample Output
<p float="left">
  <img src="https://user-images.githubusercontent.com/115461849/223998687-4ec8a8bb-9d36-4d56-9c9b-876af7bfeb96.jpg" width="400" />
</p>

2023-03-09 10:40 UTC, yasirinitialcode commented
I worked on main because i had already started when we talked about it, i'll create develop after merging this PR.

2023-03-09 10:40 UTC, yasirinitialcode commented
One PR only includes resources.

2023-03-09 15:57 UTC, bsoykal requested changes
Please apply the visual improvements I mentioned.

2023-03-09 15:57 UTC, bsoykal commented on app/src/main/java/com/netmera/netmerafintech/data/model/Favorites.kt
> +    var favoriteId: Int? = null,
A.O.

2023-03-09 15:57 UTC, bsoykal commented on app/src/main/java/com/netmera/netmerafintech/data/model/Transaction.kt
> +    var iconContainerColor: Int = R.color.blue,
A.O.

2023-03-09 15:57 UTC, bsoykal commented on app/src/main/java/com/netmera/netmerafintech/ui/decorators/DividerItemDecorator.kt
> +package com.netmera.netmerafintech.ui.decorators
/*
 * Copyright (c) 2023 Netmera.
 */

Please also apply this copyright info to all of the other classes.

2023-03-09 15:57 UTC, bsoykal commented on app/src/main/java/com/netmera/netmerafintech/ui/home/TransactionsAdapter.kt
> +    private val context: Context,
A.O.

2023-03-09 15:57 UTC, bsoykal commented on app/src/main/java/com/netmera/netmerafintech/ui/payments/ContactRecyclerAdapter.kt
> +    object ContactsComparator : DiffUtil.ItemCallback<Contact>() {
Please add comments

2023-03-09 15:57 UTC, bsoykal commented on app/src/main/java/com/netmera/netmerafintech/ui/payments/PayAgainRecyclerAdapter.kt
> +    object FavoritesComparator : DiffUtil.ItemCallback<Favorites>() {
Comments are missing

2023-03-09 15:57 UTC, bsoykal commented on app/src/main/java/com/netmera/netmerafintech/ui/payments/PaymentsFragment.kt
> +    private val onContactsClick = { contact: Contact ->
A.O.

2023-03-09 15:57 UTC, bsoykal commented on app/src/main/java/com/netmera/netmerafintech/ui/payments/PaymentsViewModel.kt
> +    private val _contactsList = MutableLiveData<List<Contact>>()
A.O.

2023-03-09 15:57 UTC, bsoykal commented on app/src/main/res/values/strings.xml
>      <string name="current_account_uppercase">CURRENT ACCOUNT</string>
You can also set this programmatically.

2023-03-09 17:13 UTC, ensar-initialcode requested changes
Still needs small changes

2023-03-09 17:13 UTC, ensar-initialcode commented on app/src/main/java/com/netmera/netmerafintech/data/Enums.kt
> +    CARD_BLACK(0),
Don't need to add card anymore. You can simply name it as `Black`, `Blue` and `Yellow`

2023-03-09 17:13 UTC, ensar-initialcode commented on app/src/main/res/values/strings.xml
>      <string name="current_account_uppercase">CURRENT ACCOUNT</string>
Yes, that would be better

2023-03-09 20:47 UTC, ensar-initialcode approved these changes

2023-03-10 12:53 UTC, bsoykal approved these changes
Very good, thank you.

2023-03-10 12:58 UTC, merged