- Send money activity has been designed.
Netmera/netmera-fintech-android pull request #4
Opened 2023-03-14 17:53 UTC by yasirinitialcode

ISSUE LINK: https://app.asana.com/0/1203144541549209/1204097456360678

## Description
- Send money page was designed.
- Dark theme issue was solved.
- Manage card page has been made dynamic.
- google-services.json file has been added.
- Visual improvements was made.
- Previews of previous and next pages in viewpager has been set up.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?
- Tested with Redmi Note 7, Huawei nova 5i, Samsung Galaxy M12

## Screenshots or Sample Output
<p float="left">
  <img src="https://user-images.githubusercontent.com/115461849/225093983-08391022-e7fe-429f-aa3c-e7535f08f79c.jpg" width="400" />
</p>

https://user-images.githubusercontent.com/115461849/225093985-b1a28c48-c17d-4ea8-96c6-7bbba9e5a3c7.mp4

https://user-images.githubusercontent.com/115461849/225093937-38ce8d52-8b17-4f7f-9b7c-5339d6ab336f.mp4

2023-03-14 18:16 UTC, bsoykal requested changes

2023-03-14 18:16 UTC, bsoykal commented on app/google-services.json
Please add this file to gitignore

2023-03-14 18:21 UTC, bsoykal requested changes
Please see my inline comments

2023-03-14 18:21 UTC, bsoykal commented on app/src/main/java/com/netmera/netmerafintech/ui/home/ManageCardActivity.kt
> +        fun open(activity: Activity?, card: Card) {
Please change it to "start"

2023-03-14 18:21 UTC, bsoykal commented on app/src/main/java/com/netmera/netmerafintech/ui/payments/SendMoneyActivity.kt
> +        fun open(activity: Activity?, favorite: Favorites) {
Please change it to "start"

2023-03-14 18:21 UTC, bsoykal commented on app/src/main/java/com/netmera/netmerafintech/utils/Extensions.kt
>      Toast.makeText(this, message, Toast.LENGTH_SHORT).show()
Adding toast length as a parameter would be nice. And the default value should be LONG because of long texts.

2023-03-14 18:32 UTC, ensar-initialcode commented on app/google-services.json
And add this file to our google drive and notion pls :)

2023-03-14 18:32 UTC, ensar-initialcode commented on app/src/main/java/com/netmera/netmerafintech/ui/home/ManageCardActivity.kt
> +            if (card.cardId == CardType.BLACK.value) {
Using `when` would be more wise here :)

2023-03-14 18:32 UTC, ensar-initialcode commented on app/src/main/java/com/netmera/netmerafintech/ui/home/ManageCardActivity.kt
> +            supportLayout.setOnClickListener { toast( "Support event was called.") }
You can move these to `setOnClickActions` method

2023-03-14 18:32 UTC, ensar-initialcode commented on app/src/main/java/com/netmera/netmerafintech/ui/payments/SendMoneyActivity.kt
> +            toast("Error occurred while opening send money. Please try again.")
```suggestion
            toast("Error occurred while opening send money page. Please try again.")
```

2023-03-14 18:32 UTC, ensar-initialcode commented on app/src/main/res/values-night/themes.xml
> +        <!-- Disabling darko mode over api level 29 -->
```suggestion
        <!-- Disabling dark mode over api level 29 -->
```

2023-03-15 12:45 UTC, ensar-initialcode commented on app/src/main/java/com/netmera/netmerafintech/ui/home/ManageCardActivity.kt
> +        @JvmStatic
We don't need `JvmStatic` in this project since all classes written with Kotlin :) You can remove them from the entire project.

2023-03-15 12:45 UTC, ensar-initialcode approved these changes

2023-03-16 16:42 UTC, bsoykal approved these changes

2023-03-16 16:51 UTC, merged