- Firebase integration has been done and some events hav been set up.
Netmera/netmera-fintech-android pull request #6
Opened 2023-03-17 09:52 UTC by yasirinitialcode

## Related Issue
- Integration of Firebase.

ISSUE LINK: https://app.asana.com/0/1203144541549209/1204097456360678

## Description

- Firebase has been integrated into project.
- Some events were set up.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- Events were observed in Firebase console.

## Screenshots or Sample Output

<p float="left">
  <img src="https://user-images.githubusercontent.com/115461849/225871277-41647bd0-08c6-4e68-8d4f-feba2ec69cd3.png" width="400" />
<img src="https://user-images.githubusercontent.com/115461849/225871284-3d36ed72-e76e-417f-8ad9-5d4399ca17eb.png" width="400" />
</p>

2023-03-17 13:27 UTC, ghost reviewed
Thank you, but small changes needed

2023-03-17 13:27 UTC, ghost commented on app/src/main/java/com/netmera/netmerafintech/ui/home/HomeFragment.kt
> +        transaction.transactionId?.let { AnalyticsUtil.paymentDetailEvent(it) }
You should do this check inside `AnalyticsUtil.paymentDetailEvent` IMO

2023-03-17 13:27 UTC, ghost commented on app/src/main/java/com/netmera/netmerafintech/ui/home/ManageCardActivity.kt
> +            it.classLoader = ManageCardActivity::class.java.classLoader
Why did you add `classLoader`?

2023-03-17 13:27 UTC, ghost commented on app/src/main/java/com/netmera/netmerafintech/ui/payments/SendMoneyActivity.kt
> +                if (amount.text.toString() != "" || amount.text.toString() != "0.00") {
Shouldn't it be `AND`?
```suggestion
                if (amount.text.toString() != "" && amount.text.toString() != "0.00") {
```

2023-03-17 13:27 UTC, ghost commented on app/src/main/java/com/netmera/netmerafintech/utils/AnalyticUtils.kt
> +    }
Can you divide this file as `NetmeraAnalyticsUtil` and `FirebaseAnalyticsUtil`? Then you can call it like
```suggestion
    fun manageEvent() {
        NetmeraAnalyticsUtil.manageEvent()
        FirebaseAnalyticsUtil.manageEvent()
    }
```

2023-03-17 13:27 UTC, ghost commented on app/src/main/java/com/netmera/netmerafintech/utils/AnalyticUtils.kt
> +    }
That would be more organized.

2023-03-17 14:29 UTC, yasirinitialcode commented on app/src/main/java/com/netmera/netmerafintech/ui/payments/SendMoneyActivity.kt
> +                if (amount.text.toString() != "" || amount.text.toString() != "0.00") {
You're right.

2023-03-17 14:30 UTC, yasirinitialcode commented on app/src/main/java/com/netmera/netmerafintech/ui/home/ManageCardActivity.kt
> +            it.classLoader = ManageCardActivity::class.java.classLoader
There was a issue called `Class not found when unmarshalling`. That is the recommended solution.

2023-03-17 14:38 UTC, ghost commented on app/src/main/java/com/netmera/netmerafintech/ui/home/ManageCardActivity.kt
> +            it.classLoader = ManageCardActivity::class.java.classLoader
Can you share the issue and recommended solution here. I would like to take a look

2023-03-17 14:45 UTC, yasirinitialcode commented on app/src/main/java/com/netmera/netmerafintech/ui/home/ManageCardActivity.kt
> +            it.classLoader = ManageCardActivity::class.java.classLoader
https://stackoverflow.com/a/28589962

2023-03-17 16:49 UTC, ensar-initialcode commented on app/src/main/java/com/netmera/netmerafintech/utils/IAnalyticsUtil.kt
> +interface IAnalyticsUtil {
Very good.

2023-03-17 16:49 UTC, ensar-initialcode approved these changes
Thank you

2023-03-17 21:45 UTC, bsoykal approved these changes
Good job, but please also add setUserId on the Firebase side.

2023-03-17 21:45 UTC, bsoykal commented on app/src/main/java/com/netmera/netmerafintech/utils/AnalyticsUtil.kt
> +        NetmeraAnalyticsUtil.updateUser()
You can also set userId on the firebase side.

2023-03-20 08:18 UTC, bsoykal requested changes

2023-03-20 08:18 UTC, bsoykal commented on app/src/main/java/com/netmera/netmerafintech/utils/AnalyticsUtil.kt
> +    override fun userUpdate() {
We should create a user class and pass all attributes as a method parameter.

2023-03-20 15:51 UTC, bsoykal approved these changes
Please adjust the toast message, which I have mentioned. Thank you

2023-03-20 15:51 UTC, bsoykal commented on app/src/main/java/com/netmera/netmerafintech/ui/splash/SplashActivity.kt
>                  toast("User update was done and sign in event and was called")
The user update is completed and the sign-In event was sent.

2023-03-20 18:38 UTC, merged